/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.RecipeWriteDto
import org.openapitools.client.models.AmountDto

class RecipeWriteDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RecipeWriteDto
        //val modelInstance = RecipeWriteDto()

        // to test the property `title`
        should("test title") {
            // uncomment below to test the property
            //modelInstance.title shouldBe ("TODO")
        }

        // to test the property `subtitle`
        should("test subtitle") {
            // uncomment below to test the property
            //modelInstance.subtitle shouldBe ("TODO")
        }

        // to test the property `labels`
        should("test labels") {
            // uncomment below to test the property
            //modelInstance.labels shouldBe ("TODO")
        }

        // to test the property `image` - image as URL
        should("test image") {
            // uncomment below to test the property
            //modelInstance.image shouldBe ("TODO")
        }

        // to test the property `imageBase64` - Base64 encoded image data (optional, can be used instead of image URL)
        should("test imageBase64") {
            // uncomment below to test the property
            //modelInstance.imageBase64 shouldBe ("TODO")
        }

        // to test the property `duration` - Duration in minutes
        should("test duration") {
            // uncomment below to test the property
            //modelInstance.duration shouldBe ("TODO")
        }

        // to test the property `ingredients`
        should("test ingredients") {
            // uncomment below to test the property
            //modelInstance.ingredients shouldBe ("TODO")
        }

        // to test the property `nutrients`
        should("test nutrients") {
            // uncomment below to test the property
            //modelInstance.nutrients shouldBe ("TODO")
        }

        // to test the property `preparation`
        should("test preparation") {
            // uncomment below to test the property
            //modelInstance.preparation shouldBe ("TODO")
        }

    }
}
