/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.RecipePromptDto

class RecipePromptDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RecipePromptDto
        //val modelInstance = RecipePromptDto()

        // to test the property `prompt` - The prompt to generate recipes, e.g. \"Generate a recipe for a low-carb dinner with chicken and vegetables.
        should("test prompt") {
            // uncomment below to test the property
            //modelInstance.prompt shouldBe ("TODO")
        }

    }
}
