/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.DefaultApi
import org.openapitools.client.models.RecipePromptDto
import org.openapitools.client.models.RecipeReadDto
import org.openapitools.client.models.RecipeWriteDto

class DefaultApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DefaultApi
        //val apiInstance = DefaultApi()

        // to test createRecipes
        should("test createRecipes") {
            // uncomment below to test createRecipes
            //val recipeWriteDto : kotlin.collections.List<RecipeWriteDto> =  // kotlin.collections.List<RecipeWriteDto> | Recipes in JSON array format.
            //val result : kotlin.collections.List<RecipeReadDto> = apiInstance.createRecipes(recipeWriteDto)
            //result shouldBe ("TODO")
        }

        // to test createRecipesWithAI
        should("test createRecipesWithAI") {
            // uncomment below to test createRecipesWithAI
            //val recipePromptDto : RecipePromptDto =  // RecipePromptDto | Recipe prompts in JSON array format.
            //val result : RecipeReadDto = apiInstance.createRecipesWithAI(recipePromptDto)
            //result shouldBe ("TODO")
        }

        // to test deleteAllRecipes
        should("test deleteAllRecipes") {
            // uncomment below to test deleteAllRecipes
            //apiInstance.deleteAllRecipes()
        }

        // to test deleteRecipeById
        should("test deleteRecipeById") {
            // uncomment below to test deleteRecipeById
            //val id : kotlin.String = id_example // kotlin.String | The Id of the recipe
            //val result : RecipeReadDto = apiInstance.deleteRecipeById(id)
            //result shouldBe ("TODO")
        }

        // to test getActualMenu
        should("test getActualMenu") {
            // uncomment below to test getActualMenu
            //val random : kotlin.Boolean = true // kotlin.Boolean | Get a random menu or the actual menu
            //val result : kotlin.collections.List<RecipeReadDto> = apiInstance.getActualMenu(random)
            //result shouldBe ("TODO")
        }

        // to test getAllRecipes
        should("test getAllRecipes") {
            // uncomment below to test getAllRecipes
            //val result : kotlin.collections.List<RecipeReadDto> = apiInstance.getAllRecipes()
            //result shouldBe ("TODO")
        }

        // to test getRecipeById
        should("test getRecipeById") {
            // uncomment below to test getRecipeById
            //val id : kotlin.String = id_example // kotlin.String | The Id of the recipe
            //val result : RecipeReadDto = apiInstance.getRecipeById(id)
            //result shouldBe ("TODO")
        }

        // to test updateMenu
        should("test updateMenu") {
            // uncomment below to test updateMenu
            //val recipeReadDto : kotlin.collections.List<RecipeReadDto> =  // kotlin.collections.List<RecipeReadDto> | Recipes for the new menu
            //val result : kotlin.collections.List<RecipeReadDto> = apiInstance.updateMenu(recipeReadDto)
            //result shouldBe ("TODO")
        }

    }
}
