/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param name 
 * @param amount 
 * @param unit 
 */
@Serializable

data class AmountDto (

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "amount") val amount: kotlin.Int? = null,

    @SerialName(value = "unit") val unit: AmountDto.Unit? = null

) {

    /**
     * 
     *
     * Values: g,kg,St,ml,l,Esslöfel,Teelöfel,kcal
     */
    @Serializable
    enum class Unit(val value: kotlin.String) {
        @SerialName(value = "g") g("g"),
        @SerialName(value = "kg") kg("kg"),
        @SerialName(value = "St") St("St"),
        @SerialName(value = "ml") ml("ml"),
        @SerialName(value = "l") l("l"),
        @SerialName(value = "Esslöfel") Esslöfel("Esslöfel"),
        @SerialName(value = "Teelöfel") Teelöfel("Teelöfel"),
        @SerialName(value = "kcal") kcal("kcal");
    }

}

