/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name 
 * @param amount 
 * @param unit 
 */


data class AmountDto (

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "amount")
    val amount: kotlin.Int? = null,

    @Json(name = "unit")
    val unit: AmountDto.Unit? = null

) {

    /**
     * 
     *
     * Values: gramm,kilogramm,stueck,milliliter,liter
     */
    @JsonClass(generateAdapter = false)
    enum class Unit(val value: kotlin.String) {
        @Json(name = "gramm") gramm("gramm"),
        @Json(name = "kilogramm") kilogramm("kilogramm"),
        @Json(name = "stueck") stueck("stueck"),
        @Json(name = "milliliter") milliliter("milliliter"),
        @Json(name = "liter") liter("liter");
    }
}

