/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable as KSerializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import java.io.Serializable

/**
 * 
 *
 * @param name 
 * @param amount 
 * @param unit 
 */
@KSerializable

data class AmountDto (

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "amount")
    val amount: kotlin.Int? = null,

    @SerialName(value = "unit")
    val unit: AmountDto.Unit? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

    /**
     * 
     *
     * Values: gramm,kilogramm,stueck,milliliter,liter
     */
    @KSerializable
    enum class Unit(val value: kotlin.String) {
        @SerialName(value = "gramm") gramm("gramm"),
        @SerialName(value = "kilogramm") kilogramm("kilogramm"),
        @SerialName(value = "stueck") stueck("stueck"),
        @SerialName(value = "milliliter") milliliter("milliliter"),
        @SerialName(value = "liter") liter("liter");
    }
}

