/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AmountDto

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*
import java.io.Serializable

/**
 * 
 *
 * @param id 
 * @param title 
 * @param subtitle 
 * @param labels 
 * @param image 
 * @param duration Duration in minutes
 * @param ingredients 
 * @param nutrients 
 * @param preparation 
 */
@Serializable

data class RecipeReadDto (

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "title") @Required val title: kotlin.String,

    @SerialName(value = "subtitle") val subtitle: kotlin.String? = null,

    @SerialName(value = "labels") val labels: kotlin.collections.List<RecipeReadDto.Labels>? = null,

    @SerialName(value = "image") val image: kotlin.String? = null,

    /* Duration in minutes */
    @SerialName(value = "duration") val duration: kotlin.Int? = null,

    @SerialName(value = "ingredients") val ingredients: kotlin.collections.List<AmountDto>? = null,

    @SerialName(value = "nutrients") val nutrients: kotlin.collections.List<AmountDto>? = null,

    @SerialName(value = "preparation") val preparation: kotlin.collections.List<kotlin.String>? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

    /**
     * 
     *
     * Values: kalorienarm,fettarm,eiweiß,vegetarisch,vegan,schwein,rind,fisch,thermomix,airfryer,express
     */
    @Serializable
    enum class Labels(val value: kotlin.String) {
        @SerialName(value = "Kalorienarm") kalorienarm("Kalorienarm"),
        @SerialName(value = "Fettarm") fettarm("Fettarm"),
        @SerialName(value = "Eiweiß") eiweiß("Eiweiß"),
        @SerialName(value = "Vegetarisch") vegetarisch("Vegetarisch"),
        @SerialName(value = "Vegan") vegan("Vegan"),
        @SerialName(value = "Schwein") schwein("Schwein"),
        @SerialName(value = "Rind") rind("Rind"),
        @SerialName(value = "Fisch") fisch("Fisch"),
        @SerialName(value = "Thermomix") thermomix("Thermomix"),
        @SerialName(value = "Airfryer") airfryer("Airfryer"),
        @SerialName(value = "Express") express("Express");
    }
}

