/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AmountDto

import kotlinx.serialization.Serializable as KSerializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import java.io.Serializable

/**
 * 
 *
 * @param id 
 * @param title 
 * @param subtitle 
 * @param labels 
 * @param image 
 * @param duration Duration in minutes
 * @param ingredients 
 * @param nutrients 
 * @param preparation 
 */
@KSerializable

data class RecipeReadDto (

    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "title")
    val title: kotlin.String,

    @SerialName(value = "subtitle")
    val subtitle: kotlin.String? = null,

    @SerialName(value = "labels")
    val labels: kotlin.collections.List<RecipeReadDto.Labels>? = null,

    @SerialName(value = "image")
    val image: kotlin.String? = null,

    /* Duration in minutes */
    @SerialName(value = "duration")
    val duration: kotlin.Int? = null,

    @SerialName(value = "ingredients")
    val ingredients: kotlin.collections.List<AmountDto>? = null,

    @SerialName(value = "nutrients")
    val nutrients: kotlin.collections.List<AmountDto>? = null,

    @SerialName(value = "preparation")
    val preparation: kotlin.collections.List<kotlin.String>? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

    /**
     * 
     *
     * Values: lowcarb,lowfat,highprotein,vegetarian,pig,beef,fish,thermomix,airfryer,express
     */
    @KSerializable
    enum class Labels(val value: kotlin.String) {
        @SerialName(value = "lowcarb") lowcarb("lowcarb"),
        @SerialName(value = "lowfat") lowfat("lowfat"),
        @SerialName(value = "highprotein") highprotein("highprotein"),
        @SerialName(value = "vegetarian") vegetarian("vegetarian"),
        @SerialName(value = "pig") pig("pig"),
        @SerialName(value = "beef") beef("beef"),
        @SerialName(value = "fish") fish("fish"),
        @SerialName(value = "thermomix") thermomix("thermomix"),
        @SerialName(value = "airfryer") airfryer("airfryer"),
        @SerialName(value = "express") express("express");
    }
}

