/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AmountDto

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 * 
 *
 * @param title 
 * @param labels 
 * @param image 
 * @param duration Duration in minutes
 * @param ingredients 
 * @param nutrients 
 * @param preparation 
 */

@Serializable
data class RecipeWriteDto (

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "labels")
    val labels: kotlin.collections.List<RecipeWriteDto.Labels>? = null,

    @Json(name = "image")
    val image: String? = null,

    /* Duration in minutes */
    @Json(name = "duration")
    val duration: kotlin.Int? = null,

    @Json(name = "ingredients")
    val ingredients: kotlin.collections.List<AmountDto>? = null,

    @Json(name = "nutrients")
    val nutrients: kotlin.collections.List<AmountDto>? = null,

    @Json(name = "preparation")
    val preparation: kotlin.collections.List<kotlin.String>? = null

) {

    /**
     * 
     *
     * Values: lowcarb,lowfat,vegetarian,pig,beef,fish
     */
    @JsonClass(generateAdapter = false)
    enum class Labels(val value: kotlin.String) {
        @Json(name = "lowcarb") lowcarb("lowcarb"),
        @Json(name = "lowfat") lowfat("lowfat"),
        @Json(name = "vegetarian") vegetarian("vegetarian"),
        @Json(name = "pig") pig("pig"),
        @Json(name = "beef") beef("beef"),
        @Json(name = "fish") fish("fish");
    }
}

