/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AmountDto

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param title 
 * @param subtitle 
 * @param labels 
 * @param image 
 * @param duration Duration in minutes
 * @param ingredients 
 * @param nutrients 
 * @param preparation 
 */
@Serializable

data class RecipeReadDto (

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "title") @Required val title: kotlin.String,

    @SerialName(value = "subtitle") val subtitle: kotlin.String? = null,

    @SerialName(value = "labels") val labels: kotlin.collections.List<RecipeReadDto.Labels>? = null,

    @SerialName(value = "image") val image: kotlin.String? = null,

    /* Duration in minutes */
    @SerialName(value = "duration") val duration: kotlin.Int? = null,

    @SerialName(value = "ingredients") val ingredients: kotlin.collections.List<AmountDto>? = null,

    @SerialName(value = "nutrients") val nutrients: kotlin.collections.List<AmountDto>? = null,

    @SerialName(value = "preparation") val preparation: kotlin.collections.List<kotlin.String>? = null

) {

    /**
     * 
     *
     * Values: Kalorienarm,Fettarm,Eiweiß,Vegetarisch,Vegan,Schwein,Rind,Fisch,Thermomix,Airfryer,Express
     */
    @Serializable
    enum class Labels(val value: kotlin.String) {
        @SerialName(value = "Kalorienarm") Kalorienarm("Kalorienarm"),
        @SerialName(value = "Fettarm") Fettarm("Fettarm"),
        @SerialName(value = "Eiweiß") Eiweiß("Eiweiß"),
        @SerialName(value = "Vegetarisch") Vegetarisch("Vegetarisch"),
        @SerialName(value = "Vegan") Vegan("Vegan"),
        @SerialName(value = "Schwein") Schwein("Schwein"),
        @SerialName(value = "Rind") Rind("Rind"),
        @SerialName(value = "Fisch") Fisch("Fisch"),
        @SerialName(value = "Thermomix") Thermomix("Thermomix"),
        @SerialName(value = "Airfryer") Airfryer("Airfryer"),
        @SerialName(value = "Express") Express("Express");
    }

}

