/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param prompt The prompt to generate recipes, e.g. \"Generate a recipe for a low-carb dinner with chicken and vegetables.
 */
@Serializable

data class RecipePromptDto (

    /* The prompt to generate recipes, e.g. \"Generate a recipe for a low-carb dinner with chicken and vegetables. */
    @SerialName(value = "prompt") val prompt: kotlin.String? = null

) {


}

